# -*- coding: utf-8 -*-
"""preingreso

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xHpHnJCYczZRiOeHgSn8Sf5kWawVklS
"""

#como el programa pide agregar, mostrar, buscar, eliminar productros
# primero hay que crear cada condicion que te pide

# Versión más básica manteniendo los requisitos obligatorios (listas, bucles, condicionales)

def mostrar_menu():
    """Muestra el menú de opciones."""
    print("\n=== Sistema Básico de Gestión de Productos ===")
    print("1. Agregar producto")
    print("2. Mostrar productos")
    print("3. Buscar producto")
    print("4. Eliminar producto")
    print("5. Salir")


#el def de arriba implica los numeros y que hace cada numero para que
#el programa observe que condicion cumple para que al mostrar el menu cada codicion tenga
#su opcion y por ende, cada definicion de codigo se active

def agregar_producto(productos):
    """Permite ingresar y añadir un producto (nombre, categoría, precio)."""
    #uso tres comillas para la cadena de multiples textos para el ingreso del producto y categoria

    nombre = input("Ingrese el nombre del producto: ").strip()
    categoria = input("Ingrese la categoría del producto: ").strip()

#en este while es utilizado para ingresar el precio que corresponde (entero y positivo)
    while True:
        precio_str = input("Ingrese el precio (sin centavos): ").strip()
        if precio_str.isdigit():
            precio = int(precio_str)
            break
        else:
            print("Error: Ingrese un número entero válido para el precio.")

    productos.append([nombre, categoria, precio])
    print(f"Producto '{nombre}' agregado correctamente.")

# en la siguiente definicion comprueba si el producto ingresado esta en la lista
def mostrar_productos(productos):
    """Muestra todos los productos registrados, numerados."""
    if not productos:
        print("No hay productos registrados. Por favor, seleccione la opción 1 para agregar uno")
    else:
        print("\n=== Lista de productos ===")
        for i, prod in enumerate(productos, start=1):
            print(f"{i}. Nombre: {prod[0]} | Categoría: {prod[1]} | Precio: ${prod[2]}")

#la siguiente es para buscar un producto en la lista
def buscar_producto(productos):
    """Busca productos por nombre (búsqueda parcial)."""
    if not productos:
        print("No hay productos para buscar.")
        return

    termino = input("Ingrese el nombre del producto a buscar: ").strip().lower()
    encontrados = []

    # Uso de bucle for para encontrar los productos
    for p in productos:
        if termino in p[0].lower():
            encontrados.append(p)

    if encontrados:
        print("\nProductos encontrados:")
        for p in encontrados:
            print(f"- Nombre: {p[0]} | Categoría: {p[1]} | Precio: ${p[2]}")
    else:
        print("No se encontraron productos con ese nombre.")

#la siguiente def es para eliminar un producto
def eliminar_producto(productos):
    """Elimina un producto por su número de posición en la lista."""
    if not productos:
        print("No hay productos para eliminar.")
        return
    mostrar_productos(productos)

    # Uso de bucle while para eliminar el producto deseado
    while True:
        opcion = input("Ingrese el NÚMERO del producto a eliminar: ").strip()

        # Validacion de las condicionales
        if opcion.isdigit():
            indice = int(opcion) - 1
            if 0 <= indice < len(productos):
                eliminado = productos.pop(indice)
                print(f"Producto '{eliminado[0]}' eliminado correctamente.")
                break
            else:
                print("Número fuera de rango.")
        else:
            print("Ingrese un número válido.")

#para terminar, el siguiente es el menos que te aparecera para eleguir la opcion que quieras.
productos = []
# Uso un Bucle para el menú principal
while True:
    mostrar_menu()
    opcion = input("Seleccione una opción: ").strip()

    if opcion == "1":
        agregar_producto(productos)
    elif opcion == "2":
        mostrar_productos(productos)
    elif opcion == "3":
        buscar_producto(productos)
    elif opcion == "4":
        eliminar_producto(productos)
    elif opcion == "5":
        print("Saliendo del sistema. ¡Hasta luego!")
        break
    else:
        print("Opción no válida. Intente nuevamente.")
